package model;

import java.sql.Timestamp;

/**
 * Represents a saved matchup prediction generated by the application.
 *
 * A Matchup object stores the participating teams, predicted winner,
 * analysis summary, and metadata associated with a user's prediction.
 *
 * @author Kevin Lightfoot
 */
public class Matchup {

    /** Unique identifier for the saved matchup. */
    private int matchupId;

    /** Identifier of the user who created the prediction. */
    private int userId;

    /** First team participating in the matchup. */
    private Team teamOne;

    /** Second team participating in the matchup. */
    private Team teamTwo;

    /** Team predicted to win the matchup. */
    private Team predictedWinner;

    /** AI-generated analysis explaining the prediction. */
    private String analysisSummary;

    /** Timestamp indicating when the prediction was created. */
    private Timestamp createdAt;

    public int getMatchupId() {
        return matchupId;
    }

    public void setMatchupId(int matchupId) {
        this.matchupId = matchupId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Team getTeamOne() {
        return teamOne;
    }

    public void setTeamOne(Team teamOne) {
        this.teamOne = teamOne;
    }

    public Team getTeamTwo() {
        return teamTwo;
    }

    public void setTeamTwo(Team teamTwo) {
        this.teamTwo = teamTwo;
    }

    public Team getPredictedWinner() {
        return predictedWinner;
    }

    public void setPredictedWinner(Team predictedWinner) {
        this.predictedWinner = predictedWinner;
    }

    public String getAnalysisSummary() {
        return analysisSummary;
    }

    public void setAnalysisSummary(String analysisSummary) {
        this.analysisSummary = analysisSummary;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

}